/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Player;
import io.swagger.annotations.*;
import org.openapitools.model.PlayerListResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-12-09T21:04:10.402+01:00[Europe/Belgrade]")
@Validated
@Api(value = "team", description = "the team API")
public interface TeamApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /team/{teamID} : Get players info by teamID.
     * Get info about the players with the same team ID as teamID.
     *
     * @param teamID Id of the team. (required)
     * @param dataTime data-time of request (optional)
     * @param id id of request (optional)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @ApiOperation(value = "Get players info by teamID.", nickname = "getTeamTeamID", notes = "Get info about the players with the same team ID as teamID.", response = PlayerListResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = PlayerListResponse.class),
        @ApiResponse(code = 404, message = "Not Found"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/team/{teamID}",
        produces = { "application/json" }
    )
    default ResponseEntity<PlayerListResponse> getTeamTeamID(@ApiParam(value = "Id of the team.", required = true) @PathVariable("teamID") String teamID, @ApiParam(value = "data-time of request") @RequestHeader(value = "Data-time", required = false) String dataTime, @ApiParam(value = "id of request") @RequestHeader(value = "Id", required = false) String id) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"firstName\" : \"Kamil\", \"lastName\" : \"Grosicki\", \"goalsCount\" : 10, \"nationality\" : \"PL\", \"assistCount\" : 7, \"id\" : \"123e4567-e89b-42d3-a456-556642440000\", \"position\" : { \"position\" : \"ST\" }, \"team\" : { \"name\" : \"Pogon Szczecin\", \"id\" : \"97874567-e89b-42d3-a456-556642440000\" }, \"age\" : 23, \"yellowCardCount\" : 3, \"redCardCount\" : 1, \"height\" : 180 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
